# Generated by Django 5.0.4 on 2024-05-23 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockUpdates',
            fields=[
                ('update_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID de actualización')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('reason', models.TextField(verbose_name='Motivo')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.products', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Actualización de stock',
                'verbose_name_plural': 'Actualizaciones de stock',
                'ordering': ['date', 'product', 'user'],
            },
        ),
    ]
