# Generated by Django 5.0.4 on 2024-05-23 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID de orden')),
                ('date_of_purchase', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de compra')),
                ('order_status', models.CharField(max_length=20, verbose_name='Estado de la orden')),
            ],
            options={
                'verbose_name': 'Orden',
                'verbose_name_plural': 'Ordenes',
            },
        ),
    ]
