# Generated by Django 5.0.4 on 2024-05-24 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(default='imagen_default.png', upload_to='product', verbose_name='Imagen'),
        ),
    ]
