# Generated by Django 5.0.4 on 2024-05-24 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_products_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproducts',
            name='image',
            field=models.TextField(default='imagen_default.png', max_length=100, verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(default='imagen_default.png', upload_to='product', verbose_name='Imagen'),
        ),
    ]
