# Generated by Django 5.0.4 on 2024-05-18 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proveedor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('price', models.FloatField(verbose_name='Precio')),
                ('stock', models.IntegerField(verbose_name='Cantidad en stock')),
                ('image', models.ImageField(upload_to='product_images', verbose_name='Imagen')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedor.providers', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
    ]
